name: Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # Required for creating releases

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Decode Debug Keystore
        run: |
          echo "Decoding and installing debug keystore..."
          mkdir -p ~/.config/.android

          echo "${DEBUG_KEYSTORE_B64}" | base64 --decode > ~/.config/.android/debug.keystore
          ls -l ~/.config/.android/debug.keystore
          echo "Debug keystore installed."
        env:
          DEBUG_KEYSTORE_B64: ${{ secrets.DEBUG_KEYSTORE_B64 }}

      - name: Build Debug APK
        working-directory: ./app
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Rename APK
        run: |
          mv ./app/app/build/outputs/apk/debug/app-debug.apk ./app/app/build/outputs/apk/debug/ha-live-${{ steps.version.outputs.VERSION }}.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: ./app/app/build/outputs/apk/debug/ha-live-${{ steps.version.outputs.VERSION }}.apk
